# register to intercept kubedb CRD creates / updates
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.kubedb.com
  labels:
    app: kubedb
webhooks:
  - name: pgbouncer.validators.kubedb.com
    clientConfig:
      service:
        namespace: default
        name: kubernetes
        path: /apis/validators.kubedb.com/v1alpha1/pgbouncervalidators
      caBundle:
    rules:
      - apiGroups: ["kubedb.com"]
        apiVersions: ["*"]
        resources: ["pgbouncers"]
        operations: ["CREATE", "UPDATE", "DELETE"]
    failurePolicy: Fail
    sideEffects: None
---
# register to intercept kubedb CRD creates / updates
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutators.kubedb.com
  labels:
    app: kubedb
webhooks:
  - name: pgbouncer.mutators.kubedb.com
    clientConfig:
      service:
        namespace: default
        name: kubernetes
        path: /apis/mutators.kubedb.com/v1alpha1/pgbouncermutators
      caBundle:
    rules:
      - apiGroups: ["kubedb.com"]
        apiVersions: ["*"]
        resources: ["pgbouncers"]
        operations: ["CREATE", "UPDATE"]
    failurePolicy: Fail
    sideEffects: None
