apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: restic-init-pg
  namespace: demo
spec:
  version: "10.2-v2"
  databaseSecret:
    secretName: scheduled-pg-auth
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: WipeOut
  init:
    stashSource:
      name: restore-session-name
