apiVersion: kubedb.com/v1alpha1
kind: PgBouncer
metadata:
  name: pgbouncer-server-2
  namespace: demo
spec:
  version: "1.9.0-r"
  replicas: 3
  databases:
  - Alias: "postgress"
    databaseName: "postgres"
    appBindingName: "quick-postgress"
    appBindingNamespace: "demo"
  connectionPool:
    listenPort: 5433
    adminUsers:
    - admin
    - admin1 
  secretList:
  - name: quick-postgress-auth
    namespace: demo
  - name: admin-secret
    namespace: demo
