apiVersion: kubedb.com/v1alpha1
kind: PgBouncer
metadata:
  name: pgbouncer-server
  namespace: demo
spec:
  version: "1.11.0"
  replicas: 1
  databases:
  - alias: "postgres"
    databaseName: "postgres"
    appBindingName: "quick-postgress"
    appBindingNamespace: "demo"
  - alias: "postgres2"
    databaseName: "tmpdb"
    appBindingName: "quick-postgress"
  connectionPool:
    maxClientConn: 20
    reservePoolSize: 5
    listenPort: 5432
    adminUsers:
    - admin
    - admin1
  userList:
    secretName: db-user-pass
    secretNamespace: demo
  monitor:
    agent: prometheus.io/builtin
