apiVersion: kubedb.com/v1alpha1
kind: PgBouncer
metadata:
  name: pgbouncer-server
  namespace: demo
spec:
  version: "1.11.0"
  replicas: 1
  databases:
  - alias: "postgres"
    databaseName: "postgres"
    databaseRef:
      name: "quick-postgress"
    username: "postgres"
    password: "Ss9sL6xFAAdEKu4D"
  - alias: "postgres2"
    databaseName: "tmpdb"
    databaseRef:
      name: "quick-postgress"
  connectionPool:
    maxClientConn: 20
    reservePoolSize: 5
    authType: "any"
    adminUsers:
    - admin
    - admin1
  userListSecretRef:
    name: db-user-pass
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: monitoring
      labels:
        k8s-app: prometheus
      interval: 10s
